### PR TITLE
Do not require argparse, decorator, and simplejson in Python 2.7.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
Only lower.

### CODE REVIEW

**Comment by datakurre** [comment]
:+1:, but just wondering, could we already use environmental markers like 

    extras_require={
        ':python_version=="2.6"': ['argparse'],
    }

**Comment by jensens** [comment]
environmental markers .. I was not aware of them. Are they already supported in Python 2.[6|7]?

**Comment by mauritsvanrees** [comment]
I think that depends on the setuptools version.

From looking at the draft at https://www.python.org/dev/peps/pep-0496/ I think it should then be:

``` python
install_requires = [
    ...
    'argparse: python_version=="2.6"',
]
```
But I get errors then:

```
 $ python2.7 setup.py egg_info
error in plone.app.robotframework setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in argparse: python_version=="2.6" at : python_version=="2.6"
```

**Comment by mauritsvanrees** [comment]
If we know how and if the environment markers work, we can revisit this. Grepping for python_version in all setup.py files in coredev gives me nothing.
I will merge as is.

**Pull request merged**
