### PR TITLE
upgrade KGS

### PR DESCRIPTION
**Pull request by gotcha**
All plone.app.robotframework tests pass.
Same for collective.ckeditor tests...

### CODE REVIEW

**Comment by jensens** [comment]
@plone/testing-team which version of firefox is running at our jenkins setup?

**Comment by gforcada** [comment]
@jensens it is versin 46: https://github.com/plone/plone.jenkins_node/blob/master/defaults/main.yml

**Comment by gotcha** [comment]
Is there a way to prove that it would work on Jenkins with Firefox 57 ?

**Comment by gforcada** [comment]
@gotcha at least not right now with small effort, specially with firefox and selenium that starting from some recent releases the driver got split out of the firefox binary and the new one is not so stable...

**Comment by gotcha** [comment]
@gforcada Did you try latest versions ? It has stabilized a lot in my opinion.

**Comment by gforcada** [comment]
@gotcha no I did not, any pointers on how to install and configure it would of course speed it up 😃

**Comment by gforcada** [comment]
@gotcha I just tried locally and after installing the geckodriver I can run robot tests on my firefox 58 🎉 

Now the question is: on jenkins nodes we can only have one version of Firefox installed, but upgrading it means that we need to install the geckodriver and bump selenium versions.

@plone/framework-team @plone/release-team would it be ok to do a major bump of versions on selenium and related packages on 4.3, 5.0 and 5.1 ? I would be 👍 on it as they are just testing dependencies, but that's only my opinion...

**Comment by jensens** [comment]
Imo, Yes, we should upgrade all supported Plone versions. Robottests must run against real environments, and after automatically upgrades of Firefox on Desktops are the gold standard now, almost nobody uses an outdated Firefox.

**Comment by jensens** [comment]
Also this would make local testing much more approachable.

**Comment by mauritsvanrees** [comment]
Fine with me to make PRs to bump versions in all coredev branches.

I have recently installed `chromedriver`, which means I can run robot tests again, so I started wondering if we should install that on Jenkins. But if `geckodriver` does the job, then that is fine with me.

I found these links which seem to explain the situation with firefox/geckodriver/selenium well:
- https://www.quora.com/Why-should-I-use-the-Gecko-Driver-in-Selenium-3-0
- https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by mauritsvanrees** [comment]
@gforcada I think we should use one driver. Independently of this issue I was thinking of chromedriver because that is more recent than what we currently have. But if geckodriver (which I didn't know yet) works good, then we can use that instead.

We *could* run robot tests with a second browser. Maybe an extra job that only runs once a week. But if Plone works fine on Firefox, then it probably works fine on Chrome as well, and the other way around. It is much more likely that something works there, but goes wrong on IE or Edge.

**Comment by tisto** [comment]
+1 to all comments. We have to make sure to keep our drivers and browsers up to date.

**Comment by datakurre** [comment]
@gforcada @gotcha I'm sorry I'm late on this. I assume it is ok to merge this, because coredev has its own pins anyway?

I had the same feelings about geckodriver + Firefox, but since Firefox 57 was released, I have no longer had issues it that personally. Also, since the latest  selenium[2]library release, also chromeheadless and firefoxheadless are supported directly (obviously either chromedriver or geckodriver must still exist).

**Comment by hvelarde** [comment]
I was able to [run collective.cover tests sucessfully](https://github.com/collective/collective.cover/pull/784) with this KGS; the only issue now is to define a canonical way to install geckodriver as Travis doesn't provide one.

**Comment by hvelarde** [comment]
@plone/framework-team tests are passing in all Plone versions, but 4.3; IMO this can be merged now.

**Comment by ale-rt** [comment]
@gotcha I think this can be closed because on buildout coredev we already have newer versions: https://github.com/plone/buildout.coredev/blob/c2c5fcf978d51581e61725e0373aeb9b376cfdfc/versions.cfg#L110-L119

**Pull request closed without merging**
