### PR TITLE
Try out robotframework-seleniumtestability for robot test stability

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
didn't see #137 ... sorry ...

**Comment by datakurre** [comment]
Did it work? I saw JS errors in geckodriver log and did not resolve that yet.

**Comment by petschki** [comment]
buildout broke because of unpinned packages ... need to make a PR in buildout.coredev first ...

**Comment by petschki** [comment]
I also see many warnings about javascript errors, but the tests are getting green:

```
[ WARN ] Message: javascript error: Cannot read properties of undefined (reading 'when')
JavaScript stack:
TypeError: Cannot read properties of undefined (reading 'when')
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:5:28)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:8:8)
    at executeAsyncScript (<anonymous>:552:47)
    at <anonymous>:567:29
    at callFunction (<anonymous>:446:22)
    at <anonymous>:460:23
    at <anonymous>:461:3
  (Session info: headless chrome=101.0.4951.64)
```

**Comment by petschki** [comment]
so despite of JS errors, the tests are all green ... maybe we could even revert those extra wait keywords implemented here https://github.com/plone/plone.app.robotframework/pull/136 in favor of this plugin ...

**Comment by fredvd** [comment]
> so despite of JS errors, the tests are all green ... maybe we could even revert those extra wait keywords implemented here #136 in favor of this plugin ...

The keywords Maurits added as a convience were already added in quite some places in 2021 when we had to fix many robot tests for the bootstrap 5 updates.  I don't get the impression they slow down the current tests a lot it's not literal sleep commands, but working around scroll into viewport bugs in selenium2. 

To make ourselves dependable on yet another .0.0 plugin that doesn't seem too stable and acts like  a magic wand...  Lets first wait for a flakey test where we can verify it does something/anything over multiple runs.

**Comment by petschki** [comment]
Fair enough ... I'll close this one as its only an experiment

**Pull request closed without merging**
