### PR TITLE
Add TEST_SCOPE_WSGI_SERVER_FIXTURE and use it in PLONE_ROBOT_TESTING …

### PR DESCRIPTION
**Pull request by datakurre**
…layer (used by Volto Cypress tests

### CODE REVIEW

**Comment by datakurre** [comment]
@jenkins-plone-org please run jobs

**Comment by sneridagh** [comment]
I just tested it and locally seems to work well. Of course, I have no means to "slow down" the processing to match the GHA runners pace. I just restarted the failing test. I will try to test this in a PR.

**Comment by datakurre** [comment]
Good to know test passed on second run. I could not find clear reason for the possible regression. WSGI shutdown should not affect the db.

**Comment by sneridagh** [comment]
Four runs, and all passed. Certainly this made impact on the test run. I'd say let's merge the other PR and this one, release p.a.robotframework.

For the record:
https://github.com/plone/volto/runs/6335283483?check_suite_focus=true

**Review by mauritsvanrees — APPROVED** [review]
I have merged the branch from PR #132 into this PR. Looks okay now.

**Comment by mauritsvanrees** [comment]
@sneridagh I have merged the two branches. Can you check if it works now? I hope I did not misinterpret some things.

In your Volto PR, the `DockerfileRF` should use p.a.robotframework master. And you should use the new layer `VOLTO_ROBOT_TESTING`.

**Comment by sneridagh** [comment]
OK! I think Asko wanted to fiddle a bit more with this one, but don't worry, we can open another PR for continue fiddling with it. The changes seemed already giving good vibrations.

Could we have another alpha release so we can test it in Volto?

Thanks!!

**Comment by sneridagh** [comment]
Regarding the DockerfileRF, I will take care of it and cleaning up after we end with the tests.

**Comment by mauritsvanrees** [comment]
I have released `plone.app.robotframework 2.0.0a4`.

**Comment by sneridagh** [comment]
Thanks!

**Comment by datakurre** [comment]
@mauritsvanrees I am sorry, but this was not yet ready :(

I though "in progress" label would have messaged that.

The merged version introduced unnecessary logging, but maybe that's not so harmful.

**Comment by sneridagh** [comment]
@datakurre Not a big deal!

What about this: 
- Remove the logging, release another alpha.
- We create another PR with the current state, update Volto's PR to match it, so @datakurre can continue doing tests
- I'm already another PR running with a4, let's see the outcome

**Comment by datakurre** [comment]
@sneridagh @mauritsvanrees Now that I saw what was merged, no reason to panic.

This pull was not complete, because it did not really fix the issue in Volto yet. But thanks to the other merge, this only introduced the new layer only into a new VOLTO_ROBOT_TESTING.

So, @sneridagh could now work to change Volto core to use plone.app.robotframework.testing.VOLTO_ROBOT_TESTING. It does not fix the issue, but should not any new issues either.

Becase PLONE_ROBOT_TESTING fixture was left untouched, merging this pull should have had no regression.

**Comment by datakurre** [comment]
Need to add one  more comment just to praise all the work @mauritsvanrees does for Plone releases :rocket:

**Comment by sneridagh** [comment]
@datakurre I will! 
let me know if you create another PR in here, so I will update the PR we were working on as well.

**Comment by mauritsvanrees** [comment]
Sorry, I merged too soon apparently. I don't think there is any harm in the currently released version though. Happy to do another release when needed.

**Pull request merged**
