### PR TITLE
Replace WSGI_SERVER_TEST_SCOPE_FIXTURE with WSGI_SERVER_SINGLE_THREAD…

### PR DESCRIPTION
**Pull request by datakurre**
…ED_FIXTURE

### CODE REVIEW

**Comment by datakurre** [comment]
@jenkins-plone-org please run jobs

**Review by sneridagh — APPROVED** [review]
LGTM! Sorry I've been busy these days... I've run it multiple times in:

https://github.com/plone/volto/actions/runs/2299491310

and worked well... time to merge and release?

**Review by jensens — APPROVED** [review]

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
I have released `plone.app.robotframework` 2.0.0a6.

**Comment by sneridagh** [comment]
@mauritsvanrees thanks!

**Pull request merged**
