### PR TITLE
Support playwright based robot tests via robotframework-browser extension

### PR DESCRIPTION
**Pull request by gforcada**
__Big disclaimer:__ I'm (@gforcada) merely the one that created the PR, the code and credits for this feature, as commits show, goes to @datakurre ✨ 💯 

⚠️ It needs the version pins defined on [this buildout.coredev branch](https://github.com/plone/buildout.coredev/tree/datakurre-rfbrowser).

Part of https://github.com/plone/Products.CMFPlone/issues/3813

### CODE REVIEW

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by datakurre** [comment]
Note about the current version pins:

Until https://github.com/robocorp/robotframework-lsp/issues/947 has been fixed and new robotframework-lsp extension for VSCode released, we must use

robotframework==6.0.2

and robotframework-lsp VSCode extension 1.10.2 to be able to use VSCode integration in collective.recipe.vscode.

Once LSP has been fixed, the latest versions should work again.

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
