### PR TITLE
Use Plone5.2 + python3.7 by default to test this package

### LINKED ISSUE #103: Test on Plone 5.2 different Python versions

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #103

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
Do we still want to support travis? 🤔 seems that the trend now is to use GitHub Actions, some packages already have it, others not, and what is being tested is rather different in each case 😕

**Comment by petschki** [comment]
travis.yml got already removed from master ... thats the conflict

**Comment by ale-rt** [comment]
Yeah, this PR is definitely obsolete!
Closing it :)

**Pull request closed without merging**
