### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
@datakurre I hope that deleting the buildout configuration is fine, if you can also double check the dependencies it would be great as well ✨ 

Tests seem to fail locally, not sure if they need more dependencies, or rather more time to run ? 🤔

### CODE REVIEW

**Review by mauritsvanrees — COMMENTED** [review]
The changes seem fine.
The failing tests obviously not.  I don't have an immediate idea what the cause could be.  I have started one Jenkins job.

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
I removed 3 GHA to get this to pass:

- tests / coverage: somehow they do not run fine on GHA 🤔 but do pass on Jenkins 🤷🏾 
- circular dependencies: there is one such between `Products.CMFPlone` and `plone.app.multilingual` ⛓️ 

Without these actions, the PR should pass fine and thus we can start benefiting from `plone/meta` DevX 🥳

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
